# Generated by Django 5.0.2 on 2024-06-04 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="pharmacyID",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="doctorID",
        ),
        migrations.DeleteModel(
            name="managment",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="patientID",
        ),
        migrations.RemoveField(
            model_name="pharmacist",
            name="pharmacyID",
        ),
        migrations.RemoveField(
            model_name="reception",
            name="refound_id",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="refound_id",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="data",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="reservation",
            name="adults",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="childs",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="depart",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="destination",
            field=models.CharField(default="Dubai", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="infants",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Specialty",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Pharmacist",
        ),
        migrations.DeleteModel(
            name="Pharmacy",
        ),
        migrations.DeleteModel(
            name="Reception",
        ),
        migrations.DeleteModel(
            name="Refound",
        ),
    ]
