# Generated by Django 5.0.6 on 2024-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocking_timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_expired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_attempts',
        ),
    ]
